### ISSUE TITLE
support atlas with multiple png files

### ISSUE THREAD

**Issue by write3371** [Nattsu39/spine-exporter#1]
support .atlas with multiple .png files
```
1.png
size: 4096,256
format: RGBA8888
filter: Linear,Linear
repeat: none

2.png
size: 4096,256
format: RGBA8888
filter: Linear,Linear
repeat: none


```

**Comment by Nattsu39** [comment]
Sorry, I haven't had much time lately, I'll get to it sometime. Can you provide an example resource?

**Comment by MirrorCY** [comment]
> Sorry, I haven't had much time lately, I'll get to it sometime. Can you provide an example asset?

https://bafybeibia3n33etoce3oz4n7s7pm5kf32xkyefyziampblhywwdd43jlcq.ipfs.dweb.link?filename=HeroBG1416_Lv2.zip

**Comment by Nattsu39** [comment]
> > Sorry, I haven't had much time lately, I'll get to it sometime. Can you provide an example asset?
> 
> https://bafybeibia3n33etoce3oz4n7s7pm5kf32xkyefyziampblhywwdd43jlcq.ipfs.dweb.link?filename=HeroBG1416_Lv2.zip
> 
> 哦对了，NSFW 注意

这下应该可以导出多纹理的资源了，不过你提供的这个资源是使用Spine 4.1版本导出的，所以暂时用不了。
