### ISSUE TITLE
canvas-size参数失效

### ISSUE THREAD

**Issue by crqrobdla** [Nattsu39/spine-exporter#2]
想問canvas-size設定 我想導出的文件因為攻擊特效所以動畫邊界很大,角色相對小 以為canvas-size可以調整但動畫邊界基本上沒有動  我以為設定500x500就是輸出500x500
另外當動畫邊界過大 輸出檔案會錯誤 請問這是電腦的問題還是ffmpeg的限制 若是ffmpeg的限制有沒有一個極限值

**Comment by crqrobdla** [comment]
更正不是基本沒有動 應該是到某個一定值就不能在小了 是不能切到動畫嗎 好像也只能自己裁剪影片了

**Comment by Nattsu39** [comment]
我检查一下，方便提供下动画源文件吗

**Comment by Nattsu39** [comment]
正常来说设置canvas-size相当于强制固定动画边界，如果动画超出这个边界就会切掉

**Comment by crqrobdla** [comment]
[nero.zip](https://github.com/user-attachments/files/16938330/nero.zip)
順便說明我的命令行

spine-export-cli export C:\Users\USER\Desktop\animation --exporter-max-concurrent 1 --selected-animation attack --scale 0.2 --canvas-size 500x500 --fps 60 -pma true -e mov
(2010x1660)

spine-export-cli export C:\Users\USER\Desktop\animation --exporter-max-concurrent 1 --selected-animation attack --scale 0.2 --fps 60 -pma true -e mov
(4276x3736)

**Comment by Nattsu39** [comment]
我稍后修复一下

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Nattsu39** [comment]
修复了这个问题，不过这个动画文件的视点（动画边界）是比较奇怪的，之后会添加一个新的选项以手动指定视点位置。
