### ISSUE TITLE
導出動畫錯誤

### ISSUE THREAD

**Issue by crqrobdla** [Nattsu39/spine-exporter#3]
抱歉又開一個issue 在導出動畫發生錯誤
**Asset export error！
asset: poon
error: Error: Region not found in atlas:  purple_fl_main_glow (mesh attachment: purple_fl_main_glow)**

應該是檔案的問題 我用另一個軟件也是報這個錯誤 
[poon (2).zip](https://github.com/user-attachments/files/17072297/poon.2.zip)
能幫我解決這個問題嗎 謝謝

**Comment by Nattsu39** [comment]
我晚点检查一下

**Comment by Nattsu39** [comment]
poon.atlas第七行`purple_fl_main_glow`有一个错误的缩进，删掉再试试

**Comment by Nattsu39** [comment]
确实是存在问题，但是我今晚可能没时间修好

________________________________
发件人: crqrobdla ***@***.***>
发送时间: 星期五, 九月 20, 2024 4:46:13 下午
收件人: Nattsu39/spine-exporter ***@***.***>
抄送: Nattsu39 ***@***.***>; Comment ***@***.***>
主题: Re: [Nattsu39/spine-exporter] С赢e` (Issue #3)


] 是竽e`

―

**Comment by crqrobdla** [comment]
沒關係 不急 我可以等 感謝幫忙

**Comment by crqrobdla** [comment]
啊我解決了 好像是空格的問題 把poon.skel和poon.atles的 ` purple_fl_main_glow` 改成 `_purple_fl_main_glow` 就成功輸出了 抱歉打擾了

**Comment by Nattsu39** [comment]
诶，我刚想回复你来着。
确实是这个问题，`TextureAtlasReader`在加载atlas时会去除每一行的空白符，但加载skel时为原样载入，这会导致名称不一致的问题。我刚才使用官方网页运行时检查了一下，也是无法浏览的，所以这应该不是一个bug。

________________________________
